title: Philipp Schwartenbeck
email: pschwartenbeck@gmail.com
description: >-
  Principal AI Engineer.
baseurl: "" # leave empty if using custom domain
url: "https://pspck.com" # your custom domain
author: Philipp Schwartenbeck

# Navigation links
header_pages:
  - about.md
  - posts.md

# Social links (only GitHub, Scholar, LinkedIn)
social_links:
  - platform: github
    user_url: https://github.com/YOUR_GITHUB_USERNAME
  - platform: google_scholar
    user_url: https://scholar.google.com/citations?user=YOUR_ID
  - platform: linkedin
    user_url: https://www.linkedin.com/in/YOUR_LINKEDIN_USERNAME

# Theme
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional: show excerpts on post listings
show_excerpts: true
