title: Philipp Schwartenbeck
# email: pschwartenbeck@gmail.com
# description: >-
  # Principal AI Engineer
baseurl: "" # leave empty if using custom domain
url: "https://pspck.com" # your custom domain

# Navigation links
header_pages:
  - about.md
  # - posts.md
  - science.md

# Theme
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional: show excerpts on post listings
show_excerpts: true
